config/routes.rb
Rails.application.routes.draw do
 
get "/" => "phone_book#index"

get "contacts/:id/edit" => "phone_book#edit", as: "edit_picture"
patch "contacts/:id" => "phone_book#update", as: "contact"

get "contacts" => "phone_book#index"

get "contacts/new" => "phone_book#new"
post "contacts" => "phone_book#create"

delete 'contacts/:id' => 'phone_book#destroy', as: "delete_contact"



end

app/models/Contact.rb
class Contact < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/phone_book_controller.rb
class PhoneBookController < ApplicationController
    def index
        @contacts = Contact.all
    end

    def new
        @contact = Contact.new
    end

    def create
        @contact = Contact.new(contact_params)
        if @contact.save
            redirect_to contacts_url
        else 
            render :new 
        end
    end

    def edit
        @contact = Contact.find(params[:id])
    end

    def update
        @contact = Contact.find(params[:id])

        if @contact.update(contact_params)
            redirect_to contacts_url
        else
            render :edit
        end
    end

    def destroy
        @contact = Contact.find(params[:id])
        @contact.destroy
        redirect_to contacts_url
    end


    private

def contact_params
    params.require(:contact).permit(:name, :number)
end    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phone_book_helper.rb
module PhoneBookHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhoneBook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/phone_book/edit.html.erb
<%= link_to "back to home", contacts_path %>


<%= form_for @contact do |f| %>

    <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
    </div>

        <div>
    <%= f.label :number %>
    <%= f.number_field :number %>
    </div>

    <div>
    <%= f.submit %>
    </div>

<% end %>

app/views/phone_book/index.html.erb
<h1>This is Dovids Phone Book (the third one)</h1>

 <%= link_to "add new", contacts_new_path  %>
<ul>
<% @contacts.each do |c| %>
    <li><%= c.name %> 
    <p><%= c.number %> <%= link_to "edit", edit_picture_path(c) %> <%= link_to "destroy", delete_contact_path(c), method: :delete, data: {confirm: "please do not destroy me!!!"} %></p>
    </li>
<% end %>
</ul>

app/views/phone_book/new.html.erb
<%= link_to "back to home", contacts_path %>


<%= form_for(@contact) do |f| %>
    <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
    </div>

        <div>
    <%= f.label :number %>
    <%= f.number_field :number %>
    </div>

<div>
<%= f.submit %>
</div>

<% end %>
  